# GitHub Actions Workflow for ML Pipeline
name: Titanic ML CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.6'

      - name: Install dependencies
        run: |                         
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run training script
        run: |
          cd scripts/ && python train_model.py